// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Fvj45vNZeQgVDFxfxzKW_2tC6_BUYaU',
    appId: '1:114616389564:web:1def233350041d69c865b9',
    messagingSenderId: '114616389564',
    projectId: 'finance-e8061',
    authDomain: 'finance-e8061.firebaseapp.com',
    storageBucket: 'finance-e8061.firebasestorage.app',
    measurementId: 'G-V562WWJP9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0MOPYK7veuMNPyOdtZR3DYXCfxM1XzoY',
    appId: '1:114616389564:android:b7b22de7167e2b50c865b9',
    messagingSenderId: '114616389564',
    projectId: 'finance-e8061',
    storageBucket: 'finance-e8061.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Fvj45vNZeQgVDFxfxzKW_2tC6_BUYaU',
    appId: '1:114616389564:web:65d14bca4dd9e01ec865b9',
    messagingSenderId: '114616389564',
    projectId: 'finance-e8061',
    authDomain: 'finance-e8061.firebaseapp.com',
    storageBucket: 'finance-e8061.firebasestorage.app',
    measurementId: 'G-EYBR63Q4LP',
  );
}
